name: Build IPA

on:
  workflow_call:
    inputs:
      projectname:
        required: true
        type: string

jobs:
  build:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: iOS Build Action
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: ${{ inputs.projectname }}.xcodeproj
          p12-base64: ${{ secrets.IOS_CERTS }}
          mobileprovision-base64: ${{ secrets.IOS_PROFILE }}
          certificate-password: ${{ secrets.IOS_CERTS_MDP }}
          export-method: development
          code-signing-identity: Apple Development
          configuration: Debug
          team-id: ${{ secrets.APPLE_TEAM_ID }}

      - name: rename IPA
        run: mv output.ipa ${{ github.event.repository.name }}.ipa
      
      
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1
        env:
          key: main
          branches: copy-push-files-branch
          files: ${{ github.event.repository.name }}.ipa
