name: Build IPA

on:
  workflow_call:
    inputs:
      projectname:
        required: true
        type: string

jobs:
  build:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Resolve XCode Dependencies
        id: resolution
        uses: GetSidetrack/action-xcodeproj-spm-update@main
        with:
          forceResolution: true
          failWhenOutdated: false

      - name: Create Pull Request
        if: steps.resolution.outputs.dependenciesChanged == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          branch: 'main'
          delete-branch: false
          commit-message: 'Update Xcode Dependencies'
          title: 'Updated Xcode Dependencies'

      - name: iOS Build Action
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: ${{ inputs.projectname }}.xcodeproj
          p12-base64: ${{ secrets.IOS_CERTS }}
          mobileprovision-base64: ${{ secrets.IOS_PROFILE }}
          certificate-password: ${{ secrets.IOS_CERTS_MDP }}
          export-method: development
          code-signing-identity: Apple Development
          configuration: Debug
          team-id: ${{ secrets.APPLE_TEAM_ID }}

      - name: rename IPA
        run: mv output.ipa ${{ github.event.repository.name }}.ipa
        
      - uses: GuillaumeFalourd/copy-push-files@v1
        with:
          source_files: ${{ github.event.repository.name }}.ipa
          remote_repository: https://github.com/GitHub-auto-build-projects/${{ github.event.repository.name }}
          access_token: ${{ secrets.GITHUB_TOKEN }}
