name: TEST Build IPA

on:
  workflow_call:
    inputs:
      projectname:
        required: true
        type: string

jobs:
  build:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: fastlane gym
